name: Build Docker image and rootfs

on: push

env:
  DOCKER_IMAGE: ysc3839/sniproxy-socks
  ROOTFS_FILE: sniproxy-socks-rootfs.tar.gz

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t $DOCKER_IMAGE .
      - uses: docker/login-action@v2
        continue-on-error: true
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker push $DOCKER_IMAGE
        continue-on-error: true
      - run: |
          CONTAINER=$(docker create $DOCKER_IMAGE)
          docker export $CONTAINER | tar --delete .dockerenv | gzip -9 - > $ROOTFS_FILE
          docker rm $CONTAINER
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ROOTFS_FILE }}
          path: ${{ env.ROOTFS_FILE }}
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.ROOTFS_FILE }}
